/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SelectOption } from "./components/select/select";
export { SelectOption } from "./components/select/select";
export namespace Components {
    interface DesignSystemDateInput {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "max": string;
        /**
          * @default ''
         */
        "min": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * @default ''
         */
        "value": string;
    }
    interface DesignSystemLoadMoreButton {
        /**
          * Disabled state
          * @default false
         */
        "disabled": boolean;
        /**
          * Text to display on the button
          * @default 'Carregar mais'
         */
        "label": string;
        /**
          * Loading state
          * @default false
         */
        "loading": boolean;
        /**
          * Loading text to display
          * @default 'Carregando...'
         */
        "loadingLabel": string;
        /**
          * Size of the button
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * Button type (button, submit, reset)
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Button variant
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary';
    }
    interface DesignSystemSearchButton {
        /**
          * Disabled state
          * @default false
         */
        "disabled": boolean;
        /**
          * Text to display on the button
          * @default 'Buscar'
         */
        "label": string;
        /**
          * Loading state
          * @default false
         */
        "loading": boolean;
        /**
          * Size of the button
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * Button type (button, submit, reset)
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Button variant
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary';
    }
    interface DesignSystemSelect {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default '[]'
         */
        "options": SelectOption[] | string;
        /**
          * @default 'Selecione uma opção'
         */
        "placeholder": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * @default ''
         */
        "value": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface DesignSystemDateInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDesignSystemDateInputElement;
}
export interface DesignSystemLoadMoreButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDesignSystemLoadMoreButtonElement;
}
export interface DesignSystemSearchButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDesignSystemSearchButtonElement;
}
export interface DesignSystemSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDesignSystemSelectElement;
}
declare global {
    interface HTMLDesignSystemDateInputElementEventMap {
        "dateChange": string;
        "dateInput": string;
    }
    interface HTMLDesignSystemDateInputElement extends Components.DesignSystemDateInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDesignSystemDateInputElementEventMap>(type: K, listener: (this: HTMLDesignSystemDateInputElement, ev: DesignSystemDateInputCustomEvent<HTMLDesignSystemDateInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDesignSystemDateInputElementEventMap>(type: K, listener: (this: HTMLDesignSystemDateInputElement, ev: DesignSystemDateInputCustomEvent<HTMLDesignSystemDateInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDesignSystemDateInputElement: {
        prototype: HTMLDesignSystemDateInputElement;
        new (): HTMLDesignSystemDateInputElement;
    };
    interface HTMLDesignSystemLoadMoreButtonElementEventMap {
        "loadMoreClick": void;
    }
    interface HTMLDesignSystemLoadMoreButtonElement extends Components.DesignSystemLoadMoreButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDesignSystemLoadMoreButtonElementEventMap>(type: K, listener: (this: HTMLDesignSystemLoadMoreButtonElement, ev: DesignSystemLoadMoreButtonCustomEvent<HTMLDesignSystemLoadMoreButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDesignSystemLoadMoreButtonElementEventMap>(type: K, listener: (this: HTMLDesignSystemLoadMoreButtonElement, ev: DesignSystemLoadMoreButtonCustomEvent<HTMLDesignSystemLoadMoreButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDesignSystemLoadMoreButtonElement: {
        prototype: HTMLDesignSystemLoadMoreButtonElement;
        new (): HTMLDesignSystemLoadMoreButtonElement;
    };
    interface HTMLDesignSystemSearchButtonElementEventMap {
        "searchClick": void;
    }
    interface HTMLDesignSystemSearchButtonElement extends Components.DesignSystemSearchButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDesignSystemSearchButtonElementEventMap>(type: K, listener: (this: HTMLDesignSystemSearchButtonElement, ev: DesignSystemSearchButtonCustomEvent<HTMLDesignSystemSearchButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDesignSystemSearchButtonElementEventMap>(type: K, listener: (this: HTMLDesignSystemSearchButtonElement, ev: DesignSystemSearchButtonCustomEvent<HTMLDesignSystemSearchButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDesignSystemSearchButtonElement: {
        prototype: HTMLDesignSystemSearchButtonElement;
        new (): HTMLDesignSystemSearchButtonElement;
    };
    interface HTMLDesignSystemSelectElementEventMap {
        "selectChange": string;
    }
    interface HTMLDesignSystemSelectElement extends Components.DesignSystemSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDesignSystemSelectElementEventMap>(type: K, listener: (this: HTMLDesignSystemSelectElement, ev: DesignSystemSelectCustomEvent<HTMLDesignSystemSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDesignSystemSelectElementEventMap>(type: K, listener: (this: HTMLDesignSystemSelectElement, ev: DesignSystemSelectCustomEvent<HTMLDesignSystemSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDesignSystemSelectElement: {
        prototype: HTMLDesignSystemSelectElement;
        new (): HTMLDesignSystemSelectElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "design-system-date-input": HTMLDesignSystemDateInputElement;
        "design-system-load-more-button": HTMLDesignSystemLoadMoreButtonElement;
        "design-system-search-button": HTMLDesignSystemSearchButtonElement;
        "design-system-select": HTMLDesignSystemSelectElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface DesignSystemDateInput {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "max"?: string;
        /**
          * @default ''
         */
        "min"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        "onDateChange"?: (event: DesignSystemDateInputCustomEvent<string>) => void;
        "onDateInput"?: (event: DesignSystemDateInputCustomEvent<string>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface DesignSystemLoadMoreButton {
        /**
          * Disabled state
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Text to display on the button
          * @default 'Carregar mais'
         */
        "label"?: string;
        /**
          * Loading state
          * @default false
         */
        "loading"?: boolean;
        /**
          * Loading text to display
          * @default 'Carregando...'
         */
        "loadingLabel"?: string;
        /**
          * Event emitted when button is clicked
         */
        "onLoadMoreClick"?: (event: DesignSystemLoadMoreButtonCustomEvent<void>) => void;
        /**
          * Size of the button
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * Button type (button, submit, reset)
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Button variant
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary';
    }
    interface DesignSystemSearchButton {
        /**
          * Disabled state
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Text to display on the button
          * @default 'Buscar'
         */
        "label"?: string;
        /**
          * Loading state
          * @default false
         */
        "loading"?: boolean;
        /**
          * Event emitted when button is clicked
         */
        "onSearchClick"?: (event: DesignSystemSearchButtonCustomEvent<void>) => void;
        /**
          * Size of the button
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * Button type (button, submit, reset)
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Button variant
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary';
    }
    interface DesignSystemSelect {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        "onSelectChange"?: (event: DesignSystemSelectCustomEvent<string>) => void;
        /**
          * @default '[]'
         */
        "options"?: SelectOption[] | string;
        /**
          * @default 'Selecione uma opção'
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "design-system-date-input": DesignSystemDateInput;
        "design-system-load-more-button": DesignSystemLoadMoreButton;
        "design-system-search-button": DesignSystemSearchButton;
        "design-system-select": DesignSystemSelect;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "design-system-date-input": LocalJSX.DesignSystemDateInput & JSXBase.HTMLAttributes<HTMLDesignSystemDateInputElement>;
            "design-system-load-more-button": LocalJSX.DesignSystemLoadMoreButton & JSXBase.HTMLAttributes<HTMLDesignSystemLoadMoreButtonElement>;
            "design-system-search-button": LocalJSX.DesignSystemSearchButton & JSXBase.HTMLAttributes<HTMLDesignSystemSearchButtonElement>;
            "design-system-select": LocalJSX.DesignSystemSelect & JSXBase.HTMLAttributes<HTMLDesignSystemSelectElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
